name: simple_mustache
description: Dart implementation of a mustache subset for simple String templates with filters.
version: 1.0.0
homepage: https://github.com/DavBfr/simple_mustache
author: David PHAM-VAN <dev.nfet.net@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test:
